name: Continous Integration

on:
  push:
    branches: [ main, feature/** ]

env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  DOCKER_REPO_NAME: ${{secrets.DOCKER_REPO_NAME}}
  
jobs:
  
  update-gitops-repo:
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v2 
      with:
        repository: lehnert-andre/argo-cd-gitops-repository
        path: './argo-cd-gitops-repository'

    - uses: imranismail/setup-kustomize@v1
    - run: |
        cd argo-cd-gitops-repository/kustomize/app/env/dev
        pwd
        kustomize edit set image alehnert/argo-cd-application-repository=alehnert/argo-cd-application-repositor:${GITHUB_SHA}
        cat kustomize.yaml
        git config --global user.email "ci@example.com"
        git config --global user.name "CI pipeline"
        git add .
        git commit -m "Set `alehnert/argo-cd-application-repository` image tag to `${GITHUB_SHA}`"
        git push
  
