name: Continous Integration

on:
  push:
    branches: [ main, feature/** ]

env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  DOCKER_REPO_NAME: ${{secrets.DOCKER_REPO_NAME}}
  ACCESS_TOKEN: ${{secrets.PERSONAL_ACCESS_TOKEN}}
  
jobs:
  push-image-to-docker-hub:
    runs-on: ubuntu-latest
    outputs:
      date: ${{ steps.tagInfo.outputs.date }}
      shaShort: ${{ steps.tagInfo.outputs.shaShort }}
    
    steps:
    - uses: actions/checkout@v2 
    
    - name: Get tag info
      id: tagInfo
      run: |
        echo "::set-output name=date::$(date +'%Y-%m-%d')"
        echo "::set-output name=shaShort::$(git rev-parse --short HEAD)"


    - name: Provide dev.env
      uses: actions/upload-artifact@master
      with:
        name: environment-file-dev
        path: environment-variables/dev/dev.env

    - name: Provide prod.env
      uses: actions/upload-artifact@master
      with:
        name: environment-file-prod
        path: environment-variables/prod/prod.env

  update-gitops-repo:
    runs-on: ubuntu-latest
    needs: push-image-to-docker-hub

    steps: 

    - name: Get dev.env
      uses: actions/download-artifact@master
      with:
        name: environment-file-dev
        path: environment-variables

    - name: Get prod.env
      uses: actions/download-artifact@master
      with:
        name: environment-file-prod
        path: environment-variables
    
    - uses: imranismail/setup-kustomize@v1
    - run: |
        export projectRoot=$(pwd)
        export tag=${{ needs.push-image-to-docker-hub.outputs.date }}-${{ needs.push-image-to-docker-hub.outputs.shaShort }}     
        git clone https://${ACCESS_TOKEN}@github.com/lehnert-andre/argo-cd-gitops-repository.git
        git config --global user.email "ci@example.com"
        git config --global user.name "CI pipeline"

        echo Update DEV
        cp ${projectRoot}/environment-variables/dev.env ${projectRoot}/argo-cd-gitops-repository/kustomize/app/env/dev/dev.env
        
        echo Update Docker Image tag on DEV
        cd ${projectRoot}/argo-cd-gitops-repository/kustomize/app/env/dev
        kustomize edit set image alehnert/argo-cd-application-repository=alehnert/argo-cd-application-repository:${tag}
        
        echo Push DEV changes
        git add .
        git commit -m "Deploy ${tag} on DEV"
        git push https://${ACCESS_TOKEN}@github.com/lehnert-andre/argo-cd-gitops-repository.git

        echo Update PROD
        cp ${projectRoot}/environment-variables/prod.env ${projectRoot}/argo-cd-gitops-repository/kustomize/app/env/prod/prod.env
        
        echo Update Docker Image tag on PROD
        cd ${projectRoot}/argo-cd-gitops-repository/kustomize/app/env/prod
        kustomize edit set image alehnert/argo-cd-application-repository=alehnert/argo-cd-application-repository:${tag}
    
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${ACCESS_TOKEN}
        commit-message: Release ${tag}
        committer: CI Pipeline
        author: CI Pipeline
        title: '[PROD] ${tag}'
        body: |
          # Release ${tag} for PROD
        assignees: lehnert-andre
